name: Release

on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - run: mvn -B clean package
      - id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./target/autocancel.hpi
          asset_name: autocancel.hpi
          asset_content_type: application/zip
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./target/autocancel.jar
          asset_name: autocancel.jar
          asset_content_type: application/zip
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: maven.jenkins-ci.org
          server-username: MVN_USERNAME
          server-password: MVN_PASSWORD
      - run: mvn -B deploy
        env:
          MVN_USERNAME: ${{ secrets.MVN_USERNAME }}
          MVN_PASSWORD: ${{ secrets.MVN_PASSWORD }}
